[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "your-project-name"
version = "0.1.0"
description = ""
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
